[package]
name = "kernel-whisperer"
version = "0.1.0"
edition = "2021"

[features]
default = []
ebpf_available = []

[dependencies]
clap        = { version = "4.5.4",  features = ["derive"] }
tokio       = { version = "1.37.0", features = ["full"] }
anyhow      = "1.0.86"
thiserror   = "1.0.61"
serde       = { version = "1.0.203", features = ["derive"] }
serde_json  = "1.0.117"
reqwest     = { version = "0.12.4", features = ["json"] }
owo-colors  = "4.0.0"
tracing     = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[profile.release]
opt-level = 3
lto       = true
strip     = true

[target.'cfg(target_os = "linux")'.dependencies]
libbpf-rs = "0.23.0"
